let countries = [];
class CountryCode {
	constructor() {
		this.short_name    = arguments[0];
		this.official_name = arguments[1];
		this.iso3 = arguments[2];
		this.iso2 = arguments[3];
		this.uni = arguments[4];
		this.undp = arguments[5];
		this.faostat = arguments[6];
		this.gaul = arguments[7];		
		this.short_name_fr = this.short_name;
		this.official_name_fr = this.official_name;
	}
}
function translateCC() {
	for(let i = 0; i < countries.length; i++) {
		if(countries[i].iso3 == arguments[2]) {
			countries[i].short_name_fr = arguments[0];
			countries[i].official_name_fr = arguments[0];
			break;
		}
	}
}
function getFrenchCountryNameFromShortName(short_name){
	for(let i = 0; i < countries.length; i++) {
		if(countries[i].short_name == short_name) {
			return countries[i].short_name_fr;
			break;
		}
	}
}
countries.push(new CountryCode("undefined", "undefined", "NULL", "999", "", "", "", ""));
countries.push(new CountryCode("Afghanistan", "the Islamic Republic of Afghanistan", "AFG", "AF", "4", "AFG", "2", "1") );
countries.push(new CountryCode("Albania", "the Republic of Albania", "ALB", "AL", "8", "ALB", "3", "3") );
countries.push(new CountryCode("Algeria", "the People's Democratic Republic of Algeria", "DZA", "DZ", "12", "DZA", "4", "4") );
countries.push(new CountryCode("Andorra", "the Principality of Andorra", "AND", "AD", "20", "AND", "6", "7") );
countries.push(new CountryCode("Angola", "the Republic of Angola", "AGO", "AO", "24", "AGO", "7", "8") );
countries.push(new CountryCode("Antigua and Barbuda", "Antigua and Barbuda", "ATG", "AG", "28", "ATG", "8", "11") );
countries.push(new CountryCode("Argentina", "the Argentine Republic", "ARG", "AR", "32", "ARG", "9", "12") );
countries.push(new CountryCode("Armenia", "the Republic of Armenia", "ARM", "AM", "51", "ARM", "1", "13") );
countries.push(new CountryCode("Australia", "Australia", "AUS", "AU", "36", "AUS", "10", "17") );
countries.push(new CountryCode("Austria", "the Republic of Austria", "AUT", "AT", "40", "AUT", "11", "18") );
countries.push(new CountryCode("Azerbaijan", "the Republic of Azerbaijan", "AZE", "AZ", "31", "AZE", "52", "19") );
countries.push(new CountryCode("Bahamas", "the Commonwealth of the Bahamas", "BHS", "BS", "44", "BHS", "12", "20") );
countries.push(new CountryCode("Bahrain", "the Kingdom of Bahrain", "BHR", "BH", "48", "BHR", "13", "21") );
countries.push(new CountryCode("Bangladesh", "the People's Republic of Bangladesh", "BGD", "BD", "50", "BGD", "16", "23") );
countries.push(new CountryCode("Barbados", "Barbados", "BRB", "BB", "52", "BRB", "14", "24") );
countries.push(new CountryCode("Belarus", "the Republic of Belarus", "BLR", "BY", "112", "BLR", "57", "26") );
countries.push(new CountryCode("Belgium", "the Kingdom of Belgium", "BEL", "BE", "56", "BEL", "255", "27") );
countries.push(new CountryCode("Belize", "Belize", "BLZ", "BZ", "84", "BLZ", "23", "28") );
countries.push(new CountryCode("Benin", "the Republic of Benin", "BEN", "BJ", "204", "BEN", "53", "29") );
countries.push(new CountryCode("Bhutan", "the Kingdom of Bhutan", "BTN", "BT", "64", "BTN", "18", "31") );
countries.push(new CountryCode("Bolivia (Plurinational State of)", "the Plurinational State of Bolivia", "BOL", "BO", "68", "BOL", "19", "33") );
countries.push(new CountryCode("Bosnia and Herzegovina", "Bosnia and Herzegovina", "BIH", "BA", "70", "BIH", "80", "34") );
countries.push(new CountryCode("Botswana", "the Republic of Botswana", "BWA", "BW", "72", "BWA", "20", "35") );
countries.push(new CountryCode("Brazil", "the Federative Republic of Brazil", "BRA", "BR", "76", "BRA", "21", "37") );
countries.push(new CountryCode("Brunei Darussalam", "Brunei Darussalam", "BRN", "BN", "96", "BRN", "26", "40") );
countries.push(new CountryCode("Bulgaria", "the Republic of Bulgaria", "BGR", "BG", "100", "BGR", "27", "41") );
countries.push(new CountryCode("Burkina Faso", "Burkina Faso", "BFA", "BF", "854", "BFA", "233", "42") );
countries.push(new CountryCode("Burundi", "the Republic of Burundi", "BDI", "BI", "108", "BDI", "29", "43") );
countries.push(new CountryCode("Cabo Verde", "Republic of Cabo Verde", "CPV", "CV", "132", "CPV", "35", "47") );
countries.push(new CountryCode("Cambodia", "the Kingdom of Cambodia", "KHM", "KH", "116", "KHM", "115", "44") );
countries.push(new CountryCode("Cameroon", "the Republic of Cameroon", "CMR", "CM", "120", "CMR", "32", "45") );
countries.push(new CountryCode("Canada", "Canada", "CAN", "CA", "124", "CAN", "33", "46") );
countries.push(new CountryCode("Central African Republic", "the Central African Republic", "CAF", "CF", "140", "CAF", "37", "49") );
countries.push(new CountryCode("Chad", "the Republic of Chad", "TCD", "TD", "148", "TCD", "39", "50") );
countries.push(new CountryCode("Chile", "the Republic of Chile", "CHL", "CL", "152", "CHL", "40", "51") );
countries.push(new CountryCode("China", "the People's Republic of China", "CHN", "CN", "156", "CHN", "41", "53") );
countries.push(new CountryCode("Colombia", "the Republic of Colombia", "COL", "CO", "170", "COL", "44", "57") );
countries.push(new CountryCode("Comoros", "the Union of the Comoros", "COM", "KM", "174", "COM", "45", "58") );
countries.push(new CountryCode("Congo", "the Republic of the Congo", "COG", "CG", "178", "COG", "46", "59") );
countries.push(new CountryCode("Cook Islands", "the Cook Islands", "COK", "CK", "184", "COK", "47", "60") );
countries.push(new CountryCode("Costa Rica", "the Republic of Costa Rica", "CRI", "CR", "188", "CRI", "48", "61") );
countries.push(new CountryCode("Croatia", "the Republic of Croatia", "HRV", "HR", "191", "HRV", "98", "62") );
countries.push(new CountryCode("Cuba", "the Republic of Cuba", "CUB", "CU", "192", "CUB", "49", "63") );
countries.push(new CountryCode("Cyprus", "the Republic of Cyprus", "CYP", "CY", "196", "CYP", "50", "64") );
countries.push(new CountryCode("Czechia", "the Czech Republic", "CZE", "CZ", "203", "CZE", "167", "65") );
countries.push(new CountryCode("Côte d'Ivoire", "the Republic of Côte d'Ivoire", "CIV", "CI", "384", "CIV", "107", "66") );
countries.push(new CountryCode("Democratic People's Republic of Korea", "the Democratic People's Republic of Korea", "PRK", "KP", "408", "PRK", "116", "67") );
countries.push(new CountryCode("Democratic Republic of the Congo", "the Democratic Republic of the Congo", "COD", "CD", "180", "COD", "250", "68") );
countries.push(new CountryCode("Denmark", "the Kingdom of Denmark", "DNK", "DK", "208", "DNK", "54", "69") );
countries.push(new CountryCode("Djibouti", "the Republic of Djibouti", "DJI", "DJ", "262", "DJI", "72", "70") );
countries.push(new CountryCode("Dominica", "the Commonwealth of Dominica", "DMA", "DM", "212", "DMA", "55", "71") );
countries.push(new CountryCode("Dominican Republic", "the Dominican Republic", "DOM", "DO", "214", "DOM", "56", "72") );
countries.push(new CountryCode("Ecuador", "the Republic of Ecuador", "ECU", "EC", "218", "ECU", "58", "73") );
countries.push(new CountryCode("Egypt", "the Arab Republic of Egypt", "EGY", "EG", "818", "EGY", "59", "40765") );
countries.push(new CountryCode("El Salvador", "the Republic of El Salvador", "SLV", "SV", "222", "SLV", "60", "75") );
countries.push(new CountryCode("Equatorial Guinea", "the Republic of Equatorial Guinea", "GNQ", "GQ", "226", "GNQ", "61", "76") );
countries.push(new CountryCode("Eritrea", "the State of Eritrea", "ERI", "ER", "232", "ERI", "178", "77") );
countries.push(new CountryCode("Estonia", "the Republic of Estonia", "EST", "EE", "233", "EST", "63", "78") );
countries.push(new CountryCode("Eswatini", "the Kingdom of Eswatini", "SWZ", "SZ", "748", "SWZ", "209", "235") );
countries.push(new CountryCode("Ethiopia", "the Federal Democratic Republic of Ethiopia", "ETH", "ET", "231", "ETH", "238", "79") );
countries.push(new CountryCode("Faroe Islands", "Faroe Islands", "FRO", "FO", "234", "FRO", "64", "82") );
countries.push(new CountryCode("Fiji", "the Republic of Fiji", "FJI", "FJ", "242", "FJI", "66", "83") );
countries.push(new CountryCode("Finland", "the Republic of Finland", "FIN", "FI", "246", "FIN", "67", "84") );
countries.push(new CountryCode("France", "the French Republic", "FRA", "FR", "250", "FRA", "68", "85") );
countries.push(new CountryCode("Gabon", "the Gabonese Republic", "GAB", "GA", "266", "GAB", "74", "89") );
countries.push(new CountryCode("Gambia", "the Republic of the Gambia", "GMB", "GM", "270", "GMB", "75", "90") );
countries.push(new CountryCode("Georgia", "Georgia", "GEO", "GE", "268", "GEO", "73", "92") );
countries.push(new CountryCode("Germany", "the Federal Republic of Germany", "DEU", "DE", "276", "DEU", "79", "93") );
countries.push(new CountryCode("Ghana", "the Republic of Ghana", "GHA", "GH", "288", "GHA", "81", "94") );
countries.push(new CountryCode("Greece", "the Hellenic Republic", "GRC", "GR", "300", "GRC", "84", "97") );
countries.push(new CountryCode("Grenada", "Grenada", "GRD", "GD", "308", "GRD", "86", "99") );
countries.push(new CountryCode("Guatemala", "the Republic of Guatemala", "GTM", "GT", "320", "GTM", "89", "103") );
countries.push(new CountryCode("Guinea", "the Republic of Guinea", "GIN", "GN", "324", "GIN", "90", "106") );
countries.push(new CountryCode("Guinea-Bissau", "the Republic of Guinea-Bissau", "GNB", "GW", "624", "GNB", "175", "105") );
countries.push(new CountryCode("Guyana", "the Co-operative Republic of Guyana", "GUY", "GY", "328", "GUY", "91", "107") );
countries.push(new CountryCode("Haiti", "the Republic of Haiti", "HTI", "HT", "332", "HTI", "93", "108") );
countries.push(new CountryCode("Honduras", "the Republic of Honduras", "HND", "HN", "340", "HND", "95", "111") );
countries.push(new CountryCode("Hungary", "Hungary", "HUN", "HU", "348", "HUN", "97", "113") );
countries.push(new CountryCode("Iceland", "the Republic of Iceland", "ISL", "IS", "352", "ISL", "99", "114") );
countries.push(new CountryCode("India", "the Republic of India", "IND", "IN", "356", "IND", "100", "115") );
countries.push(new CountryCode("Indonesia", "the Republic of Indonesia", "IDN", "ID", "360", "IDN", "101", "116") );
countries.push(new CountryCode("Iran (Islamic Republic of)", "the Islamic Republic of Iran", "IRN", "IR", "364", "IRN", "102", "117") );
countries.push(new CountryCode("Iraq", "the Republic of Iraq", "IRQ", "IQ", "368", "IRQ", "103", "118") );
countries.push(new CountryCode("Ireland", "Ireland", "IRL", "IE", "372", "IRL", "104", "119") );
countries.push(new CountryCode("Israel", "the State of Israel", "ISR", "IL", "376", "ISR", "105", "121") );
countries.push(new CountryCode("Italy", "the Republic of Italy", "ITA", "IT", "380", "ITA", "106", "122") );
countries.push(new CountryCode("Jamaica", "Jamaica", "JAM", "JM", "388", "JAM", "109", "123") );
countries.push(new CountryCode("Japan", "Japan", "JPN", "JP", "392", "JPN", "110", "126") );
countries.push(new CountryCode("Jordan", "the Hashemite Kingdom of Jordan", "JOR", "JO", "400", "JOR", "112", "130") );
countries.push(new CountryCode("Kazakhstan", "the Republic of Kazakhstan", "KAZ", "KZ", "398", "KAZ", "108", "132") );
countries.push(new CountryCode("Kenya", "the Republic of Kenya", "KEN", "KE", "404", "KEN", "114", "133") );
countries.push(new CountryCode("Kiribati", "the Republic of Kiribati", "KIR", "KI", "296", "KIR", "83", "135") );
countries.push(new CountryCode("Kuwait", "the State of Kuwait", "KWT", "KW", "414", "KWT", "118", "137") );
countries.push(new CountryCode("Kyrgyzstan", "the Kyrgyz Republic", "KGZ", "KG", "417", "KGZ", "113", "138") );
countries.push(new CountryCode("Lao People's Democratic Republic", "the Lao People's Democratic Republic", "LAO", "LA", "418", "LAO", "120", "139") );
countries.push(new CountryCode("Latvia", "the Republic of Latvia", "LVA", "LV", "428", "LVA", "119", "140") );
countries.push(new CountryCode("Lebanon", "the Lebanese Republic", "LBN", "LB", "422", "LBN", "121", "141") );
countries.push(new CountryCode("Lesotho", "the Kingdom of Lesotho", "LSO", "LS", "426", "LSO", "122", "142") );
countries.push(new CountryCode("Liberia", "the Republic of Liberia", "LBR", "LR", "430", "LBR", "123", "144") );
countries.push(new CountryCode("Libya", "State of Libya", "LBY", "LY", "434", "LBY", "124", "145") );
countries.push(new CountryCode("Lithuania", "the Republic of Lithuania", "LTU", "LT", "440", "LTU", "126", "147") );
countries.push(new CountryCode("Luxembourg", "the Grand Duchy of Luxembourg", "LUX", "LU", "442", "LUX", "256", "148") );
countries.push(new CountryCode("Madagascar", "the Republic of Madagascar", "MDG", "MG", "450", "MDG", "129", "150") );
countries.push(new CountryCode("Malawi", "the Republic of Malawi", "MWI", "MW", "454", "MWI", "130", "152") );
countries.push(new CountryCode("Malaysia", "Malaysia", "MYS", "MY", "458", "MYS", "131", "153") );
countries.push(new CountryCode("Maldives", "the Republic of Maldives", "MDV", "MV", "462", "MDV", "132", "154") );
countries.push(new CountryCode("Mali", "the Republic of Mali", "MLI", "ML", "466", "MLI", "133", "155") );
countries.push(new CountryCode("Malta", "the Republic of Malta", "MLT", "MT", "470", "MLT", "134", "156") );
countries.push(new CountryCode("Marshall Islands", "the Republic of the Marshall Islands", "MHL", "MH", "584", "MHL", "127", "157") );
countries.push(new CountryCode("Mauritania", "the Islamic Republic of Mauritania", "MRT", "MR", "478", "MRT", "136", "159") );
countries.push(new CountryCode("Mauritius", "the Republic of Mauritius", "MUS", "MU", "480", "MUS", "137", "160") );
countries.push(new CountryCode("Mexico", "the United Mexican States", "MEX", "MX", "484", "MEX", "138", "162") );
countries.push(new CountryCode("Micronesia (Federated States of)", "the Federated States of Micronesia", "FSM", "FM", "583", "FSM", "145", "163") );
countries.push(new CountryCode("Monaco", "the Principality of Monaco", "MCO", "MC", "492", "MCO", "140", "166") );
countries.push(new CountryCode("Mongolia", "Mongolia", "MNG", "MN", "496", "MNG", "141", "167") );
countries.push(new CountryCode("Montenegro", "Montenegro", "MNE", "ME", "499", "MNE", "273", "2647") );
countries.push(new CountryCode("Morocco", "the Kingdom of Morocco", "MAR", "MA", "504", "MAR", "143", "169") );
countries.push(new CountryCode("Mozambique", "the Republic of Mozambique", "MOZ", "MZ", "508", "MOZ", "144", "170") );
countries.push(new CountryCode("Myanmar", "the Republic of the Union of Myanmar", "MMR", "MM", "104", "MMR", "28", "171") );
countries.push(new CountryCode("Namibia", "the Republic of Namibia", "NAM", "NA", "516", "NAM", "147", "172") );
countries.push(new CountryCode("Nauru", "the Republic of Nauru", "NRU", "NR", "520", "NRU", "148", "173") );
countries.push(new CountryCode("Nepal", "the Federal Democratic Republic of Nepal", "NPL", "NP", "524", "NPL", "149", "175") );
countries.push(new CountryCode("Netherlands", "the Kingdom of the Netherlands", "NLD", "NL", "528", "NLD", "150", "177") );
countries.push(new CountryCode("New Zealand", "New Zealand", "NZL", "NZ", "554", "NZL", "156", "179") );
countries.push(new CountryCode("Nicaragua", "the Republic of Nicaragua", "NIC", "NI", "558", "NIC", "157", "180") );
countries.push(new CountryCode("Niger", "the Republic of the Niger", "NER", "NE", "562", "NER", "158", "181") );
countries.push(new CountryCode("Nigeria", "the Federal Republic of Nigeria", "NGA", "NG", "566", "NGA", "159", "182") );
countries.push(new CountryCode("Niue", "Niue", "NIU", "NU", "570", "NIU", "160", "183") );
countries.push(new CountryCode("North Macedonia", "the Republic of North Macedonia", "MKD", "MK", "807", "MKD", "154", "241") );
countries.push(new CountryCode("Norway", "the Kingdom of Norway", "NOR", "NO", "578", "NOR", "162", "186") );
countries.push(new CountryCode("Oman", "the Sultanate of Oman", "OMN", "OM", "512", "OMN", "221", "187") );
countries.push(new CountryCode("Pakistan", "the Islamic Republic of Pakistan", "PAK", "PK", "586", "PAK", "165", "188") );
countries.push(new CountryCode("Palau", "the Republic of Palau", "PLW", "PW", "585", "PLW", "180", "189") );
countries.push(new CountryCode("Panama", "the Republic of Panama", "PAN", "PA", "591", "PAN", "166", "191") );
countries.push(new CountryCode("Papua New Guinea", "Independent State of Papua New Guinea", "PNG", "PG", "598", "PNG", "168", "192") );
countries.push(new CountryCode("Paraguay", "the Republic of Paraguay", "PRY", "PY", "600", "PRY", "169", "194") );
countries.push(new CountryCode("Peru", "the Republic of Peru", "PER", "PE", "604", "PER", "170", "195") );
countries.push(new CountryCode("Philippines", "the Republic of the Philippines", "PHL", "PH", "608", "PHL", "171", "196") );
countries.push(new CountryCode("Poland", "the Republic of Poland", "POL", "PL", "616", "POL", "173", "198") );
countries.push(new CountryCode("Portugal", "the Portuguese Republic", "PRT", "PT", "620", "PRT", "174", "199") );
countries.push(new CountryCode("Qatar", "the State of Qatar", "QAT", "QA", "634", "QAT", "179", "201") );
countries.push(new CountryCode("Republic of Korea", "the Republic of Korea", "KOR", "KR", "410", "KOR", "117", "202") );
countries.push(new CountryCode("Republic of Moldova", "the Republic of Moldova", "MDA", "MD", "498", "MDA", "146", "165") );
countries.push(new CountryCode("Romania", "Romania", "ROU", "RO", "642", "ROU", "183", "203") );
countries.push(new CountryCode("Russian Federation", "the Russian Federation", "RUS", "RU", "643", "RUS", "185", "204") );
countries.push(new CountryCode("Rwanda", "the Republic of Rwanda", "RWA", "RW", "646", "RWA", "184", "205") );
countries.push(new CountryCode("Saint Kitts and Nevis", "Saint Kitts and Nevis", "KNA", "KN", "659", "KNA", "188", "208") );
countries.push(new CountryCode("Saint Lucia", "Saint Lucia", "LCA", "LC", "662", "LCA", "189", "209") );
countries.push(new CountryCode("Saint Vincent and the Grenadines", "Saint Vincent and the Grenadines", "VCT", "VC", "670", "VCT", "191", "211") );
countries.push(new CountryCode("Samoa", "the Independent State of Samoa", "WSM", "WS", "882", "WSM", "244", "212") );
countries.push(new CountryCode("San Marino", "the Republic of San Marino", "SMR", "SM", "674", "SMR", "192", "213") );
countries.push(new CountryCode("Sao Tome and Principe", "the Democratic Republic of Sao Tome and Principe", "STP", "ST", "678", "STP", "193", "214") );
countries.push(new CountryCode("Saudi Arabia", "the Kingdom of Saudi Arabia", "SAU", "SA", "682", "SAU", "194", "215") );
countries.push(new CountryCode("Senegal", "the Republic of Senegal", "SEN", "SN", "686", "SEN", "195", "217") );
countries.push(new CountryCode("Serbia", "the Republic of Serbia", "SRB", "RS", "688", "SRB", "272", "2648") );
countries.push(new CountryCode("Seychelles", "the Republic of Seychelles", "SYC", "SC", "690", "SYC", "196", "220") );
countries.push(new CountryCode("Sierra Leone", "the Republic of Sierra Leone", "SLE", "SL", "694", "SLE", "197", "221") );
countries.push(new CountryCode("Singapore", "the Republic of Singapore", "SGP", "SG", "702", "SGP", "200", "222") );
countries.push(new CountryCode("Slovakia", "the Slovak Republic", "SVK", "SK", "703", "SVK", "199", "223") );
countries.push(new CountryCode("Slovenia", "the Republic of Slovenia", "SVN", "SI", "705", "SVN", "198", "224") );
countries.push(new CountryCode("Solomon Islands", "Solomon Islands", "SLB", "SB", "90", "SLB", "25", "225") );
countries.push(new CountryCode("Somalia", "the Federal Republic of Somalia", "SOM", "SO", "706", "SOM", "201", "226") );
countries.push(new CountryCode("South Africa", "the Republic of South Africa", "ZAF", "ZA", "710", "ZAF", "202", "227") );
countries.push(new CountryCode("South Sudan", "the Republic of South Sudan", "SSD", "SS", "728", "SSD", "277", "74") );
countries.push(new CountryCode("Spain", "the Kingdom of Spain", "ESP", "ES", "724", "ESP", "203", "229") );
countries.push(new CountryCode("Sri Lanka", "the Democratic Socialist Republic of Sri Lanka", "LKA", "LK", "144", "LKA", "38", "231") );
countries.push(new CountryCode("Sudan", "the Republic of the Sudan", "SDN", "SD", "736", "SDN", "276", "40764") );
countries.push(new CountryCode("Suriname", "the Republic of Suriname", "SUR", "SR", "740", "SUR", "207", "233") );
countries.push(new CountryCode("Sweden", "the Kingdom of Sweden", "SWE", "SE", "752", "SWE", "210", "236") );
countries.push(new CountryCode("Switzerland", "the Swiss Confederation", "CHE", "CH", "756", "CHE", "211", "237") );
countries.push(new CountryCode("Syrian Arab Republic", "the Syrian Arab Republic", "SYR", "SY", "760", "SYR", "212", "238") );
countries.push(new CountryCode("Tajikistan", "the Republic of Tajikistan", "TJK", "TJ", "762", "TJK", "208", "239") );
countries.push(new CountryCode("Thailand", "the Kingdom of Thailand", "THA", "TH", "764", "THA", "216", "240") );
countries.push(new CountryCode("Timor-Leste", "the Democratic Republic of Timor-Leste", "TLS", "TL", "626", "TLS", "176", "242") );
countries.push(new CountryCode("Togo", "the Togolese Republic", "TGO", "TG", "768", "TGO", "217", "243") );
countries.push(new CountryCode("Tokelau", "Tokelau", "TKL", "TK", "772", "TKL", "218", "244") );
countries.push(new CountryCode("Tonga", "the Kingdom of Tonga", "TON", "TO", "776", "TON", "219", "245") );
countries.push(new CountryCode("Trinidad and Tobago", "the Republic of Trinidad and Tobago", "TTO", "TT", "780", "TTO", "220", "246") );
countries.push(new CountryCode("Tunisia", "the Republic of Tunisia", "TUN", "TN", "788", "TUN", "222", "248") );
countries.push(new CountryCode("Turkey", "the Republic of Turkey", "TUR", "TR", "792", "TUR", "223", "249") );
countries.push(new CountryCode("Turkmenistan", "Turkmenistan", "TKM", "TM", "795", "TKM", "213", "250") );
countries.push(new CountryCode("Tuvalu", "Tuvalu", "TUV", "TV", "798", "TUV", "227", "252") );
countries.push(new CountryCode("Uganda", "the Republic of Uganda", "UGA", "UG", "800", "UGA", "226", "253") );
countries.push(new CountryCode("Ukraine", "Ukraine", "UKR", "UA", "804", "UKR", "230", "254") );
countries.push(new CountryCode("United Arab Emirates", "the United Arab Emirates", "ARE", "AE", "784", "ARE", "225", "255") );
countries.push(new CountryCode("United Kingdom of Great Britain and Northern Ireland", "the United Kingdom of Great Britain and Northern Ireland", "GBR", "GB", "826", "GBR", "229", "256") );
countries.push(new CountryCode("United Republic of Tanzania", "the United Republic of Tanzania", "TZA", "TZ", "834", "TZA", "215", "257") );
countries.push(new CountryCode("United States of America", "the United States of America", "USA", "US", "840", "USA", "231", "259") );
countries.push(new CountryCode("Uruguay", "the Eastern Republic of Uruguay", "URY", "UY", "858", "URY", "234", "260") );
countries.push(new CountryCode("Uzbekistan", "the Republic of Uzbekistan", "UZB", "UZ", "860", "UZB", "235", "261") );
countries.push(new CountryCode("Vanuatu", "the Republic of Vanuatu", "VUT", "VU", "548", "VUT", "155", "262") );
countries.push(new CountryCode("Venezuela (Bolivarian Republic of)", "the Bolivarian Republic of Venezuela", "VEN", "VE", "862", "VEN", "236", "263") );
countries.push(new CountryCode("Viet Nam", "the Socialist Republic of Viet Nam", "VNM", "VN", "704", "VNM", "237", "264") );
countries.push(new CountryCode("Yemen", "the Republic of Yemen", "YEM", "YE", "887", "YEM", "249", "269") );
countries.push(new CountryCode("Zambia", "the Republic of Zambia", "ZMB", "ZM", "894", "ZMB", "251", "270") );
countries.push(new CountryCode("Zimbabwe", "the Republic of Zimbabwe", "ZWE", "ZW", "716", "ZWE", "181", "271") );




translateCC("l'inconnu", "l'inconnu", "NULL", "999", "", "", "", "");
translateCC("Afghanistan", "la République islamique d'Afghanistan", "AFG", "AF", "4", "AFG", "2", "1");
translateCC("Afrique du Sud", "la République sud-africaine", "ZAF", "ZA", "710", "ZAF", "202", "227");
translateCC("Albanie", "la République d'Albanie", "ALB", "AL", "8", "ALB", "3", "3");
translateCC("Algérie", "la République algérienne démocratique et populaire", "DZA", "DZ", "12", "DZA", "4", "4");
translateCC("Allemagne", "la République fédérale d'Allemagne", "DEU", "DE", "276", "DEU", "79", "93");
translateCC("Andorre", "la Principauté d'Andorre", "AND", "AD", "20", "AND", "6", "7");
translateCC("Angola", "la République d'Angola", "AGO", "AO", "24", "AGO", "7", "8");
translateCC("Antigua-et-Barbuda", "Antigua-et-Barbuda", "ATG", "AG", "28", "ATG", "8", "11");
translateCC("Arabie saoudite", "le Royaume d'Arabie saoudite", "SAU", "SA", "682", "SAU", "194", "215");
translateCC("Argentine", "la République argentine", "ARG", "AR", "32", "ARG", "9", "12");
translateCC("Arménie", "la République d'Arménie", "ARM", "AM", "51", "ARM", "1", "13");
translateCC("Australie", "l'Australie", "AUS", "AU", "36", "AUS", "10", "17");
translateCC("Autriche", "la République d'Autriche", "AUT", "AT", "40", "AUT", "11", "18");
translateCC("Azerbaïdjan", "la République d'Azerbaïdjan", "AZE", "AZ", "31", "AZE", "52", "19");
translateCC("Bahamas", "le Commonwealth des Bahamas", "BHS", "BS", "44", "BHS", "12", "20");
translateCC("Bahreïn", "le Royaume de Bahreïn", "BHR", "BH", "48", "BHR", "13", "21");
translateCC("Bangladesh", "la République populaire du Bangladesh", "BGD", "BD", "50", "BGD", "16", "23");
translateCC("Barbade", "la Barbade", "BRB", "BB", "52", "BRB", "14", "24");
translateCC("Belgique", "le Royaume de Belgique", "BEL", "BE", "56", "BEL", "255", "27");
translateCC("Belize", "le Belize", "BLZ", "BZ", "84", "BLZ", "23", "28");
translateCC("Bhoutan", "le Royaume du Bhoutan", "BTN", "BT", "64", "BTN", "18", "31");
translateCC("Bolivie (État plurinational de)", "l'État plurinational de Bolivie", "BOL", "BO", "68", "BOL", "19", "33");
translateCC("Bosnie-Herzégovine", "la Bosnie-Herzégovine", "BIH", "BA", "70", "BIH", "80", "34");
translateCC("Botswana", "la République du Botswana", "BWA", "BW", "72", "BWA", "20", "35");
translateCC("Brunéi Darussalam", "le Brunéi Darussalam", "BRN", "BN", "96", "BRN", "26", "40");
translateCC("Brésil", "la République fédérative du Brésil", "BRA", "BR", "76", "BRA", "21", "37");
translateCC("Bulgarie", "la République de Bulgarie", "BGR", "BG", "100", "BGR", "27", "41");
translateCC("Burkina Faso", "le Burkina Faso", "BFA", "BF", "854", "BFA", "233", "42");
translateCC("Burundi", "la République du Burundi", "BDI", "BI", "108", "BDI", "29", "43");
translateCC("Bélarus", "la République du Bélarus", "BLR", "BY", "112", "BLR", "57", "26");
translateCC("Bénin", "la République du Bénin", "BEN", "BJ", "204", "BEN", "53", "29");
translateCC("Cabo Verde", "la République de Cabo Verde", "CPV", "CV", "132", "CPV", "35", "47");
translateCC("Cambodge", "le Royaume du Cambodge", "KHM", "KH", "116", "KHM", "115", "44");
translateCC("Cameroun", "la République du Cameroun", "CMR", "CM", "120", "CMR", "32", "45");
translateCC("Canada", "le Canada", "CAN", "CA", "124", "CAN", "33", "46");
translateCC("Chili", "la République du Chili", "CHL", "CL", "152", "CHL", "40", "51");
translateCC("Chine", "la République populaire de Chine", "CHN", "CN", "156", "CHN", "41", "53");
translateCC("Chypre", "la République de Chypre", "CYP", "CY", "196", "CYP", "50", "64");
translateCC("Colombie", "la République de Colombie", "COL", "CO", "170", "COL", "44", "57");
translateCC("Comores", "l'Union des Comores", "COM", "KM", "174", "COM", "45", "58");
translateCC("Congo", "la République du Congo", "COG", "CG", "178", "COG", "46", "59");
translateCC("Costa Rica", "la République du Costa Rica", "CRI", "CR", "188", "CRI", "48", "61");
translateCC("Croatie", "la République de Croatie", "HRV", "HR", "191", "HRV", "98", "62");
translateCC("Cuba", "la République de Cuba", "CUB", "CU", "192", "CUB", "49", "63");
translateCC("Côte d'Ivoire", "la République de Côte d'Ivoire", "CIV", "CI", "384", "CIV", "107", "66");
translateCC("Danemark", "le Royaume du Danemark", "DNK", "DK", "208", "DNK", "54", "69");
translateCC("Djibouti", "la République de Djibouti", "DJI", "DJ", "262", "DJI", "72", "70");
translateCC("Dominique", "le Commonwealth de la Dominique", "DMA", "DM", "212", "DMA", "55", "71");
translateCC("El Salvador", "la République d'El Salvador", "SLV", "SV", "222", "SLV", "60", "75");
translateCC("Espagne", "le Royaume d'Espagne", "ESP", "ES", "724", "ESP", "203", "229");
translateCC("Estonie", "la République d'Estonie", "EST", "EE", "233", "EST", "63", "78");
translateCC("Eswatini", "le Royaume d’Eswatini", "SWZ", "SZ", "748", "SWZ", "209", "235");
translateCC("Fidji", "la République des Fidji", "FJI", "FJ", "242", "FJI", "66", "83");
translateCC("Finlande", "la République de Finlande", "FIN", "FI", "246", "FIN", "67", "84");
translateCC("France", "la République française", "FRA", "FR", "250", "FRA", "68", "85");
translateCC("Fédération de Russie", "la Fédération de Russie", "RUS", "RU", "643", "RUS", "185", "204");
translateCC("Gabon", "la République gabonaise", "GAB", "GA", "266", "GAB", "74", "89");
translateCC("Gambie", "la République de Gambie", "GMB", "GM", "270", "GMB", "75", "90");
translateCC("Ghana", "la République du Ghana", "GHA", "GH", "288", "GHA", "81", "94");
translateCC("Grenade", "la Grenade", "GRD", "GD", "308", "GRD", "86", "99");
translateCC("Grèce", "la République hellénique", "GRC", "GR", "300", "GRC", "84", "97");
translateCC("Guatemala", "la République du Guatemala", "GTM", "GT", "320", "GTM", "89", "103");
translateCC("Guinée", "la République de Guinée", "GIN", "GN", "324", "GIN", "90", "106");
translateCC("Guinée équatoriale", "la République de Guinée équatoriale", "GNQ", "GQ", "226", "GNQ", "61", "76");
translateCC("Guinée-Bissau", "la République de Guinée-Bissau", "GNB", "GW", "624", "GNB", "175", "105");
translateCC("Guyana", "la République coopérative du Guyana", "GUY", "GY", "328", "GUY", "91", "107");
translateCC("Géorgie", "la Géorgie", "GEO", "GE", "268", "GEO", "73", "92");
translateCC("Haïti", "la République d'Haïti", "HTI", "HT", "332", "HTI", "93", "108");
translateCC("Honduras", "la République du Honduras", "HND", "HN", "340", "HND", "95", "111");
translateCC("Hongrie", "la Hongrie", "HUN", "HU", "348", "HUN", "97", "113");
translateCC("Inde", "la République de l'Inde", "IND", "IN", "356", "IND", "100", "115");
translateCC("Indonésie", "la République d'Indonésie", "IDN", "ID", "360", "IDN", "101", "116");
translateCC("Iran (République islamique d')", "la République islamique d'Iran", "IRN", "IR", "364", "IRN", "102", "117");
translateCC("Iraq", "la République d'Iraq", "IRQ", "IQ", "368", "IRQ", "103", "118");
translateCC("Irlande", "l'Irlande", "IRL", "IE", "372", "IRL", "104", "119");
translateCC("Islande", "la République d'Islande", "ISL", "IS", "352", "ISL", "99", "114");
translateCC("Israël", "l'État d'Israël", "ISR", "IL", "376", "ISR", "105", "121");
translateCC("Italie", "la République italienne", "ITA", "IT", "380", "ITA", "106", "122");
translateCC("Jamaïque", "la Jamaïque", "JAM", "JM", "388", "JAM", "109", "123");
translateCC("Japon", "le Japon", "JPN", "JP", "392", "JPN", "110", "126");
translateCC("Jordanie", "le Royaume hachémite de Jordanie", "JOR", "JO", "400", "JOR", "112", "130");
translateCC("Kazakhstan", "la République du Kazakhstan", "KAZ", "KZ", "398", "KAZ", "108", "132");
translateCC("Kenya", "la République du Kenya", "KEN", "KE", "404", "KEN", "114", "133");
translateCC("Kirghizistan", "la République kirghize", "KGZ", "KG", "417", "KGZ", "113", "138");
translateCC("Kiribati", "la République de Kiribati", "KIR", "KI", "296", "KIR", "83", "135");
translateCC("Koweït", "l'État du Koweït", "KWT", "KW", "414", "KWT", "118", "137");
translateCC("Lesotho", "le Royaume du Lesotho", "LSO", "LS", "426", "LSO", "122", "142");
translateCC("Lettonie", "la République de Lettonie", "LVA", "LV", "428", "LVA", "119", "140");
translateCC("Liban", "la République libanaise", "LBN", "LB", "422", "LBN", "121", "141");
translateCC("Libéria", "la République du Libéria", "LBR", "LR", "430", "LBR", "123", "144");
translateCC("Lituanie", "la République de Lituanie", "LTU", "LT", "440", "LTU", "126", "147");
translateCC("Luxembourg", "le Grand-Duché de Luxembourg", "LUX", "LU", "442", "LUX", "256", "148");
translateCC("Macédoine du Nord", "la République de Macédoine du Nord", "MKD", "MK", "807", "MKD", "154", "241");
translateCC("Madagascar", "la République de Madagascar", "MDG", "MG", "450", "MDG", "129", "150");
translateCC("Malaisie", "la Malaisie", "MYS", "MY", "458", "MYS", "131", "153");
translateCC("Malawi", "la République du Malawi", "MWI", "MW", "454", "MWI", "130", "152");
translateCC("Maldives", "la République des Maldives", "MDV", "MV", "462", "MDV", "132", "154");
translateCC("Mali", "la République du Mali", "MLI", "ML", "466", "MLI", "133", "155");
translateCC("Malte", "la République de Malte", "MLT", "MT", "470", "MLT", "134", "156");
translateCC("Maroc", "le Royaume du Maroc", "MAR", "MA", "504", "MAR", "143", "169");
translateCC("Maurice", "la République de Maurice", "MUS", "MU", "480", "MUS", "137", "160");
translateCC("Mauritanie", "la République islamique de Mauritanie", "MRT", "MR", "478", "MRT", "136", "159");
translateCC("Mexique", "les États-Unis du Mexique", "MEX", "MX", "484", "MEX", "138", "162");
translateCC("Micronésie (États fédérés de)", "les États fédérés de Micronésie", "FSM", "FM", "583", "FSM", "145", "163");
translateCC("Monaco", "la Principauté de Monaco", "MCO", "MC", "492", "MCO", "140", "166");
translateCC("Mongolie", "la Mongolie", "MNG", "MN", "496", "MNG", "141", "167");
translateCC("Monténégro", "le Monténégro", "MNE", "ME", "499", "MNE", "273", "2647");
translateCC("Mozambique", "la République du Mozambique", "MOZ", "MZ", "508", "MOZ", "144", "170");
translateCC("Myanmar", "République de l'Union du Myanmar", "MMR", "MM", "104", "MMR", "28", "171");
translateCC("Namibie", "la République de Namibie", "NAM", "NA", "516", "NAM", "147", "172");
translateCC("Nauru", "la République de Nauru", "NRU", "NR", "520", "NRU", "148", "173");
translateCC("Nicaragua", "la République du Nicaragua", "NIC", "NI", "558", "NIC", "157", "180");
translateCC("Niger", "la République du Niger", "NER", "NE", "562", "NER", "158", "181");
translateCC("Nigéria", "la République fédérale du Nigéria", "NGA", "NG", "566", "NGA", "159", "182");
translateCC("Nioué", "Nioué", "NIU", "NU", "570", "NIU", "160", "183");
translateCC("Norvège", "le Royaume de Norvège", "NOR", "NO", "578", "NOR", "162", "186");
translateCC("Nouvelle-Zélande", "la Nouvelle-Zélande", "NZL", "NZ", "554", "NZL", "156", "179");
translateCC("Népal", "la République fédérale démocratique du Nepal", "NPL", "NP", "524", "NPL", "149", "175");
translateCC("Oman", "le Sultanat d'Oman", "OMN", "OM", "512", "OMN", "221", "187");
translateCC("Ouganda", "la République de l'Ouganda", "UGA", "UG", "800", "UGA", "226", "253");
translateCC("Ouzbékistan", "la République d'Ouzbékistan", "UZB", "UZ", "860", "UZB", "235", "261");
translateCC("Pakistan", "la République islamique du Pakistan", "PAK", "PK", "586", "PAK", "165", "188");
translateCC("Palaos", "la République des Palaos", "PLW", "PW", "585", "PLW", "180", "189");
translateCC("Panama", "la République du Panama", "PAN", "PA", "591", "PAN", "166", "191");
translateCC("Papouasie-Nouvelle-Guinée", "État indépendant de Papouasie-Nouvelle-Guinée", "PNG", "PG", "598", "PNG", "168", "192");
translateCC("Paraguay", "la République du Paraguay", "PRY", "PY", "600", "PRY", "169", "194");
translateCC("Pays-Bas", "le Royaume des Pays-Bas", "NLD", "NL", "528", "NLD", "150", "177");
translateCC("Philippines", "la République des Philippines", "PHL", "PH", "608", "PHL", "171", "196");
translateCC("Pologne", "la République de Pologne", "POL", "PL", "616", "POL", "173", "198");
translateCC("Portugal", "la République portugaise", "PRT", "PT", "620", "PRT", "174", "199");
translateCC("Pérou", "la République du Pérou", "PER", "PE", "604", "PER", "170", "195");
translateCC("Qatar", "l'État du Qatar", "QAT", "QA", "634", "QAT", "179", "201");
translateCC("Roumanie", "la Roumanie", "ROU", "RO", "642", "ROU", "183", "203");
translateCC("Royaume-Uni de Grande-Bretagne et d'Irlande du Nord", "le Royaume-Uni de Grande-Bretagne et d'Irlande du Nord", "GBR", "GB", "826", "GBR", "229", "256");
translateCC("Rwanda", "la République du Rwanda", "RWA", "RW", "646", "RWA", "184", "205");
translateCC("République arabe syrienne", "la République arabe syrienne", "SYR", "SY", "760", "SYR", "212", "238");
translateCC("République centrafricaine", "la République centrafricaine", "CAF", "CF", "140", "CAF", "37", "49");
translateCC("République de Corée", "la République de Corée", "KOR", "KR", "410", "KOR", "117", "202");
translateCC("République de Moldova", "la République de Moldova", "MDA", "MD", "498", "MDA", "146", "165");
translateCC("République dominicaine", "la République dominicaine", "DOM", "DO", "214", "DOM", "56", "72");
translateCC("République démocratique du Congo", "la République démocratique du Congo", "COD", "CD", "180", "COD", "250", "68");
translateCC("République démocratique populaire lao", "la République démocratique populaire lao", "LAO", "LA", "418", "LAO", "120", "139");
translateCC("République populaire démocratique de Corée", "la République populaire démocratique de Corée", "PRK", "KP", "408", "PRK", "116", "67");
translateCC("République-Unie de Tanzanie", "la République-Unie de Tanzanie", "TZA", "TZ", "834", "TZA", "215", "257");
translateCC("Saint-Kitts-et-Nevis", "Saint-Kitts-et-Nevis", "KNA", "KN", "659", "KNA", "188", "208");
translateCC("Saint-Marin", "la République de Saint-Marin", "SMR", "SM", "674", "SMR", "192", "213");
translateCC("Saint-Vincent-et-les Grenadines", "Saint-Vincent-et-les Grenadines", "VCT", "VC", "670", "VCT", "191", "211");
translateCC("Sainte-Lucie", "Sainte-Lucie", "LCA", "LC", "662", "LCA", "189", "209");
translateCC("Samoa", "l'État indépendant du Samoa", "WSM", "WS", "882", "WSM", "244", "212");
translateCC("Sao Tomé-et-Principe", "la République démocratique de Sao Tomé-et-Principe", "STP", "ST", "678", "STP", "193", "214");
translateCC("Serbie", "la République de Serbie", "SRB", "RS", "688", "SRB", "272", "2648");
translateCC("Seychelles", "la République des Seychelles", "SYC", "SC", "690", "SYC", "196", "220");
translateCC("Sierra Leone", "la République de Sierra Leone", "SLE", "SL", "694", "SLE", "197", "221");
translateCC("Singapour", "la République de Singapour", "SGP", "SG", "702", "SGP", "200", "222");
translateCC("Slovaquie", "la République slovaque", "SVK", "SK", "703", "SVK", "199", "223");
translateCC("Slovénie", "la République de Slovénie", "SVN", "SI", "705", "SVN", "198", "224");
translateCC("Somalie", "la République fédérale de Somalie", "SOM", "SO", "706", "SOM", "201", "226");
translateCC("Soudan", "la République du Soudan", "SDN", "SD", "736", "SDN", "276", "40764");
translateCC("Soudan du Sud", "République du Soudan du Sud", "SSD", "SS", "728", "SSD", "277", "74");
translateCC("Sri Lanka", "la République socialiste démocratique de Sri Lanka", "LKA", "LK", "144", "LKA", "38", "231");
translateCC("Suisse", "la Confédération suisse", "CHE", "CH", "756", "CHE", "211", "237");
translateCC("Suriname", "la République du Suriname", "SUR", "SR", "740", "SUR", "207", "233");
translateCC("Suède", "le Royaume de Suède", "SWE", "SE", "752", "SWE", "210", "236");
translateCC("Sénégal", "la République du Sénégal", "SEN", "SN", "686", "SEN", "195", "217");
translateCC("Tadjikistan", "la République du Tadjikistan", "TJK", "TJ", "762", "TJK", "208", "239");
translateCC("Tchad", "la République du Tchad", "TCD", "TD", "148", "TCD", "39", "50");
translateCC("Tchéquie", "la République tchèque", "CZE", "CZ", "203", "CZE", "167", "65");
translateCC("Thaïlande", "le Royaume de Thaïlande", "THA", "TH", "764", "THA", "216", "240");
translateCC("Timor-Leste", "la République démocratique du Timor-Leste", "TLS", "TL", "626", "TLS", "176", "242");
translateCC("Togo", "la République togolaise", "TGO", "TG", "768", "TGO", "217", "243");
translateCC("Tokélaou", "les Tokélaou", "TKL", "TK", "772", "TKL", "218", "244");
translateCC("Tonga", "le Royaume des Tonga", "TON", "TO", "776", "TON", "219", "245");
translateCC("Trinité-et-Tobago", "la République de Trinité-et-Tobago", "TTO", "TT", "780", "TTO", "220", "246");
translateCC("Tunisie", "la République tunisienne", "TUN", "TN", "788", "TUN", "222", "248");
translateCC("Turkménistan", "le Turkménistan", "TKM", "TM", "795", "TKM", "213", "250");
translateCC("Turquie", "la République turque", "TUR", "TR", "792", "TUR", "223", "249");
translateCC("Tuvalu", "les Tuvalu", "TUV", "TV", "798", "TUV", "227", "252");
translateCC("Ukraine", "l'Ukraine", "UKR", "UA", "804", "UKR", "230", "254");
translateCC("Uruguay", "la République orientale de l'Uruguay", "URY", "UY", "858", "URY", "234", "260");
translateCC("Vanuatu", "la République du Vanuatu", "VUT", "VU", "548", "VUT", "155", "262");
translateCC("Venezuela (République bolivarienne du)", "la République bolivarienne du Venezuela", "VEN", "VE", "862", "VEN", "236", "263");
translateCC("Viet Nam", "la République socialiste du Viet Nam", "VNM", "VN", "704", "VNM", "237", "264");
translateCC("Yémen", "la République du Yémen", "YEM", "YE", "887", "YEM", "249", "269");
translateCC("Zambie", "la République de Zambie", "ZMB", "ZM", "894", "ZMB", "251", "270");
translateCC("Zimbabwe", "la République du Zimbabwe", "ZWE", "ZW", "716", "ZWE", "181", "271");
translateCC("la Libye", "l'État de Libye", "LBY", "LY", "434", "LBY", "124", "145");
translateCC("Îles Cook", "les Îles Cook", "COK", "CK", "184", "COK", "47", "60");
translateCC("Îles Féroé", "les Îles Féroé", "FRO", "FO", "234", "FRO", "64", "82");
translateCC("Îles Marshall", "la République des Îles Marshall", "MHL", "MH", "584", "MHL", "127", "157");
translateCC("Îles Salomon", "les Îles Salomon", "SLB", "SB", "90", "SLB", "25", "225");
translateCC("Égypte", "la République arabe d'Égypte", "EGY", "EG", "818", "EGY", "59", "40765");
translateCC("Émirats arabes unis", "les Émirats arabes unis", "ARE", "AE", "784", "ARE", "225", "255");
translateCC("Équateur", "la République de l'Équateur", "ECU", "EC", "218", "ECU", "58", "73");
translateCC("Érythrée", "l'État d'Érythrée", "ERI", "ER", "232", "ERI", "178", "77");
translateCC("États-Unis d'Amérique", "les États-Unis d'Amérique", "USA", "US", "840", "USA", "231", "259");
translateCC("Éthiopie", "la République fédérale démocratique d'Éthiopie", "ETH", "ET", "231", "ETH", "238", "79");


